In [1]:
import pandas as pd
from transformers import BertTokenizer

In [2]:
train_df = pd.read_csv("../data/input/train.csv")
test_df = pd.read_csv("../data/input/test.csv")

In [3]:
train_df

id keyword location  \
0         1     NaN      NaN   
1         4     NaN      NaN   
2         5     NaN      NaN   
3         6     NaN      NaN   
4         7     NaN      NaN   
...     ...     ...      ...   
7608  10869     NaN      NaN   
7609  10870     NaN      NaN   
7610  10871     NaN      NaN   
7611  10872     NaN      NaN   
7612  10873     NaN      NaN   

                                                   text  target  
0     Our Deeds are the Reason of this #earthquake M...       1  
1                Forest fire near La Ronge Sask. Canada       1  
2     All residents asked to 'shelter in place' are ...       1  
3     13,000 people receive #wildfires evacuation or...       1  
4     Just got sent this photo from Ruby #Alaska as ...       1  
...                                                 ...     ...  
7608  Two giant cranes holding a bridge collapse int...       1  
7609  @aria_ahrary @TheTawniest The out of control w...       1  
7610  M1.94 [01:04 UTC]?5km S of Volcano Hawaii. htt...       1  
7611  Police investigating after an e-bike collided ...       1  
7612  The Latest: More Homes Razed by Northern Calif...       1  

[7613 rows x 5 columns]

In [4]:
train_df["text"][0].split(" ")

['Our',
 'Deeds',
 'are',
 'the',
 'Reason',
 'of',
 'this',
 '#earthquake',
 'May',
 'ALLAH',
 'Forgive',
 'us',
 'all']

In [5]:
#train_df["text_len"] = 
train_df["text"].apply(lambda x: len(x.split(" "))).max()
#display(train_df)

54

In [6]:
MAX_LEN = train_df["text"].apply(lambda x: len(x.split(" "))).max()
print(MAX_LEN)

54


# BERT Tokenizer

In [7]:
sentences = train_df.text.values
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased', do_lower_case=True)
input_ids = [
    tokenizer.encode(
        sentence, 
        add_special_tokens=True, 
        max_length=MAX_LEN,
        padding='max_length'
    )
    for sentence in sentences
]
labels = train_df.target.values

In [8]:
print("Actual sentense: ", train_df["text"][2])
print("Encoded: ", input_ids[2])

Actual sentense:  All residents asked to 'shelter in place' are being notified by officers. No other evacuation or shelter in place orders are expected
Encoded:  [101, 2035, 3901, 2356, 2000, 1005, 7713, 1999, 2173, 1005, 2024, 2108, 19488, 2011, 3738, 1012, 2053, 2060, 13982, 2030, 7713, 1999, 2173, 4449, 2024, 3517, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [9]:
import numpy as np
attention_masks = [[float(i > 0) for i in seq] for seq in input_ids]
print(type(attention_masks))
print(len(attention_masks))
print(attention_masks[:3])

<class 'list'>
7613
[[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]]


In [10]:
text = sentences[0]

tokenizer.encode_plus(
    text,
    add_special_tokens = True,
    max_length = MAX_LEN,
    padding = 'max_length', 
    truncation = True
)

{'input_ids': [101, 2256, 15616, 2024, 1996, 3114, 1997, 2023, 1001, 8372, 2089, 16455, 9641, 2149, 2035, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]}

# Another

In [21]:
import re

def preprocess_text(sentence):
    TAG_RE = re.compile(r'<[^>]+>')
    sentence = TAG_RE.sub(' ', sentence)
    sentence = re.sub('[^a-zA-Z]', ' ', sentence)
    sentence = re.sub(r"\s+[a-zA-Z]\s+", ' ', sentence)
    sentence = re.sub(r'\s+', ' ', sentence)
    return sentence

In [31]:
tweets = []
sentences = list(train_df["text"])
for sentence in sentences:
    tweets.append(preprocess_text(sentence))
print(f"tweets[0]: {tweets[10]}")

tweets[0]: Three people died from the heat wave so far


In [32]:
labels = train_df["target"].values
print(labels[:10])

[1 1 1 1 1 1 1 1 1 1]


In [33]:
import bert
import tensorflow_hub as hub

bert_layer = hub.KerasLayer(
    "https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/1",
    trainable=False
)
vocabulary_file = bert_layer.resolved_object.vocab_file.asset_path.numpy()
to_lower_case = bert_layer.resolved_object.do_lower_case.numpy()
tokenizer = bert.bert_tokenization.FullTokenizer(vocabulary_file, to_lower_case)

In [34]:
tokenized_tweets = [
    tokenizer.convert_tokens_to_ids(tokenizer.tokenize(text)) for text in tweets
]
print(f"tokenized_tweets length: {len(tokenized_tweets)}")

tokenized_tweets length: 7613


In [35]:
i = 10
print(f"original[{i}]: \n {tweets[i]}")
print(f"tokenized[{i}]: \n {tokenized_tweets[i]}")

original[10]: 
 Three people died from the heat wave so far
tokenized[10]: 
 [2093, 2111, 2351, 2013, 1996, 3684, 4400, 2061, 2521]


## Pretraining Data For Training

In [43]:
tweets_labels = [
    (tweet, labels[i]) for i, tweet in enumerate(tokenized_tweets)
]
print(f"tweets_labels[{i}]: {tweets_labels[i]}")

tweets_labels[10]: ([2093, 2111, 2351, 2013, 1996, 3684, 4400, 2061, 2521], 1)


In [52]:
import tensorflow as tf

processed_dataset = tf.data.Dataset.from_generator(
    lambda: tweets_labels,
    output_types=(tf.int32, tf.int32)
)

BATCH_SIZE = 16
batched_dataset = processed_dataset.padded_batch(
    BATCH_SIZE,
    padded_shapes=((None, ), ())
)

In [53]:
next(iter(batched_dataset))

(<tf.Tensor: shape=(16, 27), dtype=int32, numpy=
 array([[ 2256, 15616,  2024,  1996,  3114,  1997,  2023,  8372,  2089,
         16455,  9641,  2149,  2035,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0],
        [ 3224,  2543,  2379,  2474,  6902,  3351, 21871,  2243,  2710,
             0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0],
        [ 2035,  3901,  2356,  2000,  7713,  1999,  2173,  2024,  2108,
         19488,  2011,  3738,  2053,  2060, 13982,  2030,  7713,  1999,
          2173,  4449,  2024,  3517,     0,     0,     0,     0,     0],
        [ 2111,  4374,  3748, 26332, 13982,  4449,  1999,  2662,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0],
        [ 2074,  2288,  2741,  2023,  6302,  2013, 10090,  7397,  2004,
          5

In [54]:
import math
TOTAL_BATCHES = math.ceil(len(tweets_labels) / BATCH_SIZE)
TEST_BATCHES = TOTAL_BATCHES // 10
batched_dataset.shuffle(TOTAL_BATCHES)
test_data = batched_dataset.take(TEST_BATCHES)
train_data = batched_dataset.skip(TEST_BATCHES)

## Creating the Model

In [47]:
from tensorflow.keras import layers

class TEXT_MODEL(tf.keras.Model):
    def __init__(
        self,
        vocabulary_size,
        embedding_dimensions = 128,
        cnn_filters = 50,
        dnn_units = 512,
        model_output_classes = 2,
        dropout_rate = 0.1,
        training=False,
        name="text_model"
    ):
        super(TEXT_MODEL, self).__init__(name=name)
        
        self.embedding = layers.Embedding(
            vocabulary_size,
            embedding_dimensions
        )
        self.cnn_layer1 = layers.Conv1D(
            filters=cnn_filters,
            kernel_size=2,
            padding="valid",
            activation="relu"
        )
        self.cnn_layer2 = layers.Conv1D(
            filters=cnn_filters,
            kernel_size=3,
            padding="valid",
            activation="relu"
        )
        self.cnn_layer3 = layers.Conv1D(
            filters=cnn_filters,
            kernel_size=4,
            padding="valid",
            activation="relu"
        )
        self.pool = layers.GlobalMaxPool1D()
        self.dense_1 = layers.Dense(units=dnn_units, activation="relu")
        self.dropout = layers.Dropout(rate=dropout_rate)
        if model_output_classes == 2:
            self.last_dense = layers.Dense(
                units=1,
                activation="sigmoid"
            )
        else:
            self.last_dense = layers.Dense(
                units=model_output_classes,
                activation="softmax"
            )
            
    def call(self, inputs, training):
        l = self.embedding(inputs)
        l_1 = self.cnn_layer1(l)
        l_1 = self.pool(l_1)
        l_2 = self.cnn_layer2(l)
        l_2 = self.pool(l_2)
        l_3 = self.cnn_layer3(l)
        l_3 = self.pool(l_3)
        
        concatenated = tf.concat([l_1, l_2, l_3], axis=-1)
        concatenated = self.dense_1(concatenated)
        concatenated = self.dropout(concatenated, training)
        model_output = self.last_dense(concatenated)
        
        return model_output

In [55]:
VOCAB_LENGTH = len(tokenizer.vocab)
EMB_DIM = 200
CNN_FILTERS = 100
DNN_UNITS = 256
OUTPUT_CLASSES = 2
DROPOUT_RATE = 0.2
NB_EPOCHS = 5

text_model = TEXT_MODEL(
    vocabulary_size = VOCAB_LENGTH,
    embedding_dimensions=EMB_DIM,
    cnn_filters=CNN_FILTERS,
    dnn_units=DNN_UNITS,
    model_output_classes=OUTPUT_CLASSES,
    dropout_rate = DROPOUT_RATE
)

if OUTPUT_CLASSES == 2:
    text_model.compile(
        loss="binary_crossentropy",
        optimizer="adam",
        metrics=["accuracy"]
    )
else:
    text_model.compile(
        loss="sparse_categorical_crossentropy",
        optmizer="adam",
        metrics=["sparse_categorical_accuracy"]
    )
    
text_model.fit(train_data, epochs=NB_EPOCHS)

Epoch 1/5
429/429 [==============================] - 19s 44ms/step - loss: 0.6428 - accuracy: 0.6409
Epoch 2/5
429/429 [==============================] - 16s 37ms/step - loss: 0.3990 - accuracy: 0.8239
Epoch 3/5
429/429 [==============================] - 16s 38ms/step - loss: 0.1860 - accuracy: 0.9297
Epoch 4/5
429/429 [==============================] - 17s 40ms/step - loss: 0.1144 - accuracy: 0.9599
Epoch 5/5
429/429 [==============================] - 16s 38ms/step - loss: 0.0723 - accuracy: 0.9762


In [56]:
results = text_model.evaluate(test_data)

print(f"loss: {results[0]:.4f}")
print(f"accuracy: {results[1]:.4f}")

47/47 [==============================] - 0s 8ms/step - loss: 1.2516 - accuracy: 0.7234
loss: 1.2516
accuracy: 0.7234


# Create Submission